In [ ]:
# Q1 : First, after reading this data in Python,do some basic checks on the data to understand its contents.
# The data consists of ___ rows and ___ columns

#Answer 1 : 6991
#Answer 2 : 23

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("stackoverflow-1.csv",sep=",",header=0)

In [3]:
data.shape

(6991, 23)

In [ ]:
# Q2 : First, after reading this data in Python,do some basic checks on the data to understand its contents.
# There are ___ missing values in the column ___.
# (Hint: There is only one column in the data with missing values)

#Answer 1: 31
#Answer 2: CompanySizeNumber

In [4]:
data.isnull().sum()

RespondentID                               0
Country                                    0
Salary                                     0
YearsCodedJob                              0
OpenSource                                 0
Hobby                                      0
CompanySizeNumber                         31
Remote                                     0
CareerSatisfaction                         0
Datascientist                              0
Database administrator                     0
Desktop applications developer             0
Developer with stats/math background       0
DevOps                                     0
Embedded developer                         0
Graphic designer                           0
Graphics programming                       0
Machine learning specialist                0
Mobile developer                           0
Quality assurance engineer                 0
Systems administrator                      0
Web developer                              0
          

In [ ]:
# Q3 : First, after reading this data in Python , do some basic checks on the data to understand its contents.
# There are  ___ unique countries in the dataframe stackoverflow.

# Answer : 5

In [5]:
data.columns.tolist()

['RespondentID',
 'Country',
 'Salary',
 'YearsCodedJob',
 'OpenSource',
 'Hobby',
 'CompanySizeNumber',
 'Remote',
 'CareerSatisfaction',
 'Datascientist',
 'Database administrator',
 'Desktop applications developer',
 'Developer with stats/math background',
 'DevOps',
 'Embedded developer',
 'Graphic designer',
 'Graphics programming',
 'Machine learning specialist',
 'Mobile developer',
 'Quality assurance engineer',
 'Systems administrator',
 'Web developer',
 '    ']

In [6]:
data['Country'].unique()

array(['United Kingdom', 'United States', 'Germany', 'India', 'Canada'],
      dtype=object)

In [ ]:
# Q4 : First, after reading this data in Python , do some basic checks on the data to understand its contents.
# There are ___ Indian Data Scientists present in the data.
# (Hint: Filter using Country and Data scientist column)

#Answer : 43

In [7]:
data['Datascientist'].unique()

array([0, 1], dtype=int64)

In [8]:
data.query("Country == 'India' & Datascientist == 1").shape

(43, 23)

In [ ]:
# Q5 : First, after reading this data in Python , do some basic checks on the data to 
# understand its contents.
# ___ respondents work remotely in this data.
# (Hint: Calculate the total counts of label – “Remote” in the Remote column)

#Answer : 718

In [9]:
data['Remote'].unique()

array(['Not remote', 'Remote'], dtype=object)

In [10]:
data[data['Remote']=='Remote'].shape

(718, 23)

In [ ]:
# Q6 : First, after reading this data in Python , do some basic checks on the data to understand its contents.
# ___ is the count of Germans who have more than 10 years of coding experience
# (Hint: Use Country and YearsCodedJob columns)

#Answer : 181

In [11]:
data['YearsCodedJob'].unique()

array([20,  3, 16,  4,  1, 13,  7, 17, 10,  9, 14,  2,  5, 15,  8, 11,  6,
       18, 19, 12,  0], dtype=int64)

In [12]:
data.query("Country=='Germany' & YearsCodedJob > 10").shape

(181, 23)

In [ ]:
# Q7 : Now that you have the basic idea of how the data looks like, try to find group 
# wise summaries by various columns. Can you answer the following questions?

# Country _______ has maximum average Salary? (Hint: Calculate average salary by 
# countries. Fill the same label as mentioned in the data for the country that shows highest average salary.)

#Answer : United States

In [13]:
data.groupby("Country",as_index=False).agg({'Salary':np.mean}).sort_values("Salary",ascending=False)

Country        Salary
4   United States  98313.127654
0          Canada  58226.407451
3  United Kingdom  53962.871808
1         Germany  52405.823429
2           India  11557.674529

In [ ]:
# Q8 : Now that you have the basic idea of how the data looks like, try to find group wise summaries by various columns. 
# Can you answer the following questions?

# Country ________ has least remote workers (Hint: Flag Remote column as 1, 0 where 1 indicates the label Remote. 
# Then create groupby summary using Country and remote column. Enter the Country name that has least remote workers)

#Answer : Canada

In [14]:
data1 = pd.read_csv("stackoverflow-1.csv",sep=",",header=0)

In [15]:
data1['Remote'].unique()

array(['Not remote', 'Remote'], dtype=object)

In [16]:
def get_label(x):
    if x=='Remote':
        return 1
    else:
        return 0
data1['Remote']=data1['Remote'].map(get_label)

In [17]:
data1=data1[data1['Remote']==1]

In [18]:
data1['Remote'].unique()

array([1], dtype=int64)

In [19]:
data1.groupby('Country').agg({'Remote':'count'})

Remote
Country               
Canada              43
Germany             49
India               66
United Kingdom      85
United States      475

In [ ]:
#Q9 : Now that you have the basic idea of how the data looks like, try to find group wise summaries by various columns. 
# Can you answer the following questions?
# ____% is the percentage of Mobile Developers in the data. (Hint: Use Mobile Developer column. 
# The answer should be rounded off in terms of percentage. Eg. 10%)

#Answer : 19

In [20]:
total_obs = data.shape[0]
total_obs

6991

In [21]:
mob_dev = data[data['Mobile developer']==1].shape[0]
mob_dev

1356

In [22]:
per = 1356/6991
per

0.19396366757259334

In [23]:
round(0.19396366757259334*100)

19

In [ ]:
#Q10 : Now that you have the basic idea of how the data looks like, try to find group wise summaries by various columns. 
# Can you answer the following questions?
# ____% is the percentage of Web Developers in the data. (Hint: Use Web Developer column. 
# The answer should be rounded off in terms of percentage. Eg. 10%)

#Answer : 72

In [24]:
data['Web developer'].unique()

array([0, 1], dtype=int64)

In [25]:
data.shape[0]

6991

In [26]:
data[data['Web developer']==1].shape[0]

5062

In [27]:
per = 5062/6991
per

0.7240738091832356

In [28]:
round(0.7240738091832356*100)

72

In [ ]:
#Q11 : Now that you have the basic idea of how the data looks like, try to find group wise summaries by various columns. 
# Can you answer the following questions?
# ___ is the number of profiles who are Mobile Developers and Web Developers and who work remotely?
# (Hint: Use Mobile Developer,Web Developer and Remote column)

#Answer : 115

In [29]:
data1['Remote'].unique()

array([1], dtype=int64)

In [30]:
data12=data1[(data1['Mobile developer']==1) & data1['Web developer']==1]

In [31]:
data12.shape[0]

115

In [ ]:
#Q12 : Now that you have the basic idea of how the data looks like, try to find group wise summaries by various columns. 
#Can you answer the following questions?

#If we calculate the following 
#i) maximum salary and average years of coding job of profiles by each Country
#ii) sort the salary column in the output obtained in descending order
#iii) Select columns Country, Salary and YearsCodedJob

#Following is the output we get. Fill in the blanks.

#Country           Salary        YearsCodedJob
#United States     197000                 8.40
#United Kingdom    ______                 ____
#India             ______                 3.70
#Canada            151515                 ____
#Germany           140000                 7.06

#Hint - Salary column, round the values to integer "YearsCodedJob" column should be rounded to two decimal places.

#Answer :
#Country           Salary        YearsCodedJob
#United States     197000                 8.40
#United Kingdom    193750                 7.32
#India             163135                 3.70
#Canada            151515                 7.52
#Germany           140000                 7.06 

In [32]:
data=pd.read_csv('stackoverflow-1.csv',sep=',',header=0)

In [33]:
data13=data.groupby('Country').agg({'Salary':np.max,'YearsCodedJob':np.mean}).sort_values('Salary',ascending=False)

In [34]:
data13

Salary  YearsCodedJob
Country                                   
United States   197000.0000       8.397877
United Kingdom  193750.0000       7.315748
India           163134.7967       3.696697
Canada          151515.1515       7.523425
Germany         140000.0000       7.058947

In [35]:
data13['Salary']=round(data13['Salary'])

In [36]:
data13['YearsCodedJob']=round(data13['YearsCodedJob'],2)

In [37]:
data13

Salary  YearsCodedJob
Country                                
United States   197000.0           8.40
United Kingdom  193750.0           7.32
India           163135.0           3.70
Canada          151515.0           7.52
Germany         140000.0           7.06

In [ ]:
#Q13 : After creating group wise summaries to understand the data, we can create new columns in the data that can be used for 
# modelling later on –

# a. Lets say you create a new variable (Company_label) that consists of labels for CompanySizeNumber as low, medium and high. 
#You can do that by defining a function. The rows where the values of this column are less than 20, label them as low. 
#The rows where the values of this column are between 20 and 1000 label them as medium and the rows where the values of this 
#column are greater than 1000 label them as high. Once you do that what would be the frequency count for each label in the 
#newly created column – (Company_label). Fill in the blanks

# high           1530
# medium         ____
# low            ____

# (Hint: You can define a function or use nested lambda and map function to create new labels. Sample function is as below –

#                                          def new_func(x):

#                                                         if x  < 10:

#                                                               return 1

#                                                         elif  10 <= x <= 20:

#                                                               return 2

#                                                         else:

#                                                               return 3

 

# To apply this function to a column use:

#                                   data['new_Col']    =  data['Col'].map(new_func)

#Answer :
# high           1530
# medium         4305 
# low            1156

In [38]:
def new_func(x):
    if x<20:
        return 'low'
    elif 20<=x<=1000:
        return 'medium'
    else:
        return 'high'

data['Company_label']=data['CompanySizeNumber'].map(new_func)

In [39]:
data.columns.tolist()

['RespondentID',
 'Country',
 'Salary',
 'YearsCodedJob',
 'OpenSource',
 'Hobby',
 'CompanySizeNumber',
 'Remote',
 'CareerSatisfaction',
 'Datascientist',
 'Database administrator',
 'Desktop applications developer',
 'Developer with stats/math background',
 'DevOps',
 'Embedded developer',
 'Graphic designer',
 'Graphics programming',
 'Machine learning specialist',
 'Mobile developer',
 'Quality assurance engineer',
 'Systems administrator',
 'Web developer',
 '    ',
 'Company_label']

In [40]:
data['Company_label'].unique()

array(['high', 'medium', 'low'], dtype=object)

In [42]:
data.query("Company_label=='high'").shape[0]

1530

In [43]:
data.query("Company_label=='medium'").shape[0]

4305

In [44]:
data.query("Company_label=='low'").shape[0]

1156

In [ ]:
# Q14 : After creating group wise summaries to understand the data, we can create new columns in the data that can be used for 
# modelling later on –
# Create a new column to flag those who are Data scientist or a Developer with stats/math background or a Machine learning 
#specialist. _____ observations are present in the data that satisfy this condition? 

# Hint 1: Define a function or use lambda to define a function to flag those rows that satisfy the given condition as 1. 
#Create a new column to store these flagged labels. Count the no. of 1’s in a newly created column.

# Hint 2: Once you define a function use apply to create a new column. For example if the new function is called get_label use 
#the statement below to create the new column :
# data['new_col'] = data.apply(get_label,axis=1)
# Count the no. of 1’s in the data['new'] and this should give the answer to question.

#Answer : 1129

In [45]:
def get_label(x):
    if (x['Datascientist']==1 or x['Developer with stats/math background']==1 or x['Machine learning specialist']==1):
        return 1
    else:
        return 0
    
data['new_col']=data.apply(get_label,axis=1)

In [46]:
data.columns.tolist()

['RespondentID',
 'Country',
 'Salary',
 'YearsCodedJob',
 'OpenSource',
 'Hobby',
 'CompanySizeNumber',
 'Remote',
 'CareerSatisfaction',
 'Datascientist',
 'Database administrator',
 'Desktop applications developer',
 'Developer with stats/math background',
 'DevOps',
 'Embedded developer',
 'Graphic designer',
 'Graphics programming',
 'Machine learning specialist',
 'Mobile developer',
 'Quality assurance engineer',
 'Systems administrator',
 'Web developer',
 '    ',
 'Company_label',
 'new_col']

In [47]:
data['new_col'].unique()

array([0, 1], dtype=int64)

In [48]:
data[data['new_col']==1].shape[0]

1129